### PR TITLE
Fix mountinfo parsing #153

### LINKED ISSUE #153: `mount -t tmpfs - /tmp` -> "found invalid line"
... presumably because the parser splits on *all* dashes and then checks for exactly two fields. It should. instead, split on `-` with maximum two fields.

Yes, I like to call my tmpfs mounts `-`.

### PR DESCRIPTION
**Pull request by IGLOU-EU**
Quick patch to fix
#153 mount -t tmpfs - /tmp -> "found invalid line"

Split directly with strings.Fields instead of "(8) separator: marks the end of the optional fields"

Todo:
- ~~Spaces into "optional fields"~~ (The Linux kernel test does not support space on it https://github.com/torvalds/linux/blob/e55f0c439a2681a3c299bedd99ebe998049fa508/tools/testing/selftests/move_mount_set_group/move_mount_set_group_test.c#L124)
- ~~Zero optional fields~~ (It contains at least the type of mount (ro or rw) https://man7.org/linux/man-pages/man5/fstab.5.html https://man7.org/linux/man-pages/man5/proc.5.html)
- ~~Non zero super options~~
- ~~Optional fields~~ ((7)  optional fields: zero or more fields of the form "tag[:value]")

Signed-off-by: Adrien Kara <adrien@iglou.eu>

### CODE REVIEW

**Comment by muesli** [comment]
We should probably add a test for various valid and/or problematic entries.

**Comment by IGLOU-EU** [comment]
Do you have any test cases in mind ?

**Comment by muesli** [comment]
> Do you have any test cases in mind ?

- regular unproblematic entries
- certainly the problematic entry from the report in #153
- comments
- empty lines
- ...

> > The second field (fs_file) => If the name of the mount point contains spaces or tabs these can be escaped as `\040' and '\011' respectively.

That should we test for as well.

> EDIT: Because of the apparent "complexity", I think a dedicated function is needed. Don't you? If it is good for you, I will add a `mounts_linux_internal_test.go` file

I agree.

Nice work so far, will give this a proper review asap.

**Comment by IGLOU-EU** [comment]
@muesli , can you review ? :slightly_smiling_face:

**Comment by muesli** [comment]
Ok, I've simplified the mountinfo parsing a bit. Everything seems to be working and testing fine, but maybe you wanna give it one more review as well. `unescapeFstab` seems to decode the strings just fine, so I've removed the newly added `decodeName` function again.

**Comment by IGLOU-EU** [comment]
Cool, I hadn't seen it.
I'm not sure if it's a good idea to not respect the official mountinfo index, like defined by proc man pages.

**Pull request merged**
